version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - tsdb-data:/var/lib/postgresql/data
      - ./deploy/timescale/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telemetry"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.6
    container_name: grafana
    depends_on:
      - timescaledb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./deploy/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:0.64.1
    container_name: opa
    command: ["run", "--server", "/policies"]
    volumes:
      - ./deploy/opa:/policies:ro
    ports:
      - "8181:8181"
    restart: unless-stopped

volumes:
  tsdb-data:
  grafana-data:
